<?php

use App\Enums\SettingType;

return [
    /*
    |--------------------------------------------------------------------------
    | Setting Groups
    |--------------------------------------------------------------------------
    |
    | Define the groups for organizing settings in the admin panel.
    | Each group has a slug, icon, order, and translatable name/description.
    |
    */
    'groups' => [
        [
            'slug' => 'general',
            'icon' => 'cog-6-tooth',
            'order' => 1,
            'name' => ['en' => 'General', 'fr' => 'Général', 'es' => 'General'],
            'description' => ['en' => 'General system settings and preferences', 'fr' => 'Paramètres et préférences générales du système', 'es' => 'Configuración y preferencias generales del sistema'],
        ],
        [
            'slug' => 'appearance',
            'icon' => 'paint-brush',
            'order' => 2,
            'name' => ['en' => 'Appearance', 'fr' => 'Apparence', 'es' => 'Apariencia'],
            'description' => ['en' => 'Customize the look and feel of your application', 'fr' => 'Personnalisez l\'apparence de votre application', 'es' => 'Personaliza la apariencia de tu aplicación'],
        ],
        [
            'slug' => 'notifications',
            'icon' => 'bell',
            'order' => 3,
            'name' => ['en' => 'Notifications', 'fr' => 'Notifications', 'es' => 'Notificaciones'],
            'description' => ['en' => 'Configure how and when you receive notifications', 'fr' => 'Configurez comment et quand vous recevez des notifications', 'es' => 'Configura cómo y cuándo recibir notificaciones'],
        ],
        [
            'slug' => 'security',
            'icon' => 'shield-check',
            'order' => 4,
            'name' => ['en' => 'Security', 'fr' => 'Sécurité', 'es' => 'Seguridad'],
            'description' => ['en' => 'Configure security settings for your application', 'fr' => 'Configurez les paramètres de sécurité de votre application', 'es' => 'Configura los ajustes de seguridad de tu aplicación'],
        ],
        [
            'slug' => 'email',
            'icon' => 'envelope',
            'order' => 5,
            'name' => ['en' => 'Email', 'fr' => 'E-mail', 'es' => 'Correo electrónico'],
            'description' => ['en' => 'Configure email settings for your application', 'fr' => 'Configurez les paramètres d\'e-mail pour votre application', 'es' => 'Configura los ajustes de correo electrónico para tu aplicación'],
        ],
        [
            'slug' => 'attachments',
            'icon' => 'paper-clip',
            'order' => 6,
            'name' => ['en' => 'Attachments', 'fr' => 'Pièces Jointes', 'es' => 'Archivos Adjuntos'],
            'description' => ['en' => 'Configure settings for file attachments and uploads.', 'fr' => 'Configurez les paramètres pour les pièces jointes et les téléversements.', 'es' => 'Configura los ajustes para archivos adjuntos y subidas.'],
        ],
        [
            'slug' => 'site-identity',
            'icon' => 'identification',
            'order' => 7,
            'name' => ['en' => 'Site Identity', 'fr' => 'Identité du site', 'es' => 'Identidad del Sitio'],
            'description' => ['en' => 'Configure site identity settings like favicon and copyright.', 'fr' => 'Configurez les paramètres d\'identité du site comme le favicon et le copyright.', 'es' => 'Configura los ajustes de identidad del sitio como el favicon y los derechos de autor.'],
        ],
        [
            'slug' => 'integrations',
            'icon' => 'puzzle-piece',
            'order' => 8,
            'name' => ['en' => 'Integrations', 'fr' => 'Intégrations', 'es' => 'Integraciones'],
            'description' => ['en' => 'Configure settings for third-party integrations.', 'fr' => 'Configurez les paramètres pour les intégrations tierces.', 'es' => 'Configura los ajustes para integraciones de terceros.'],
        ],
        [
            'slug' => 'contact',
            'icon' => 'user-circle',
            'order' => 9,
            'name' => ['en' => 'Contact Information', 'fr' => 'Coordonnées', 'es' => 'Información de Contacto'],
            'description' => ['en' => 'Configure contact information for your site.', 'fr' => 'Configurez les coordonnées de votre site.', 'es' => 'Configura la información de contacto para tu sitio.'],
        ],
        [
            'slug' => 'seo',
            'icon' => 'chart-pie',
            'order' => 10,
            'name' => ['en' => 'SEO', 'fr' => 'SEO', 'es' => 'SEO'],
            'description' => ['en' => 'Configure SEO settings for your site.', 'fr' => 'Configurez les paramètres SEO de votre site.', 'es' => 'Configura los ajustes SEO de tu sitio.'],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Settings
    |--------------------------------------------------------------------------
    */
    'settings' => [
        // General Settings
        [
            'group' => 'general',
            'key' => 'site_name',
            'value' => 'My Awesome Site',
            'type' => SettingType::TEXT,
            'is_public' => true,
            'is_required' => true,
            'validation_rules' => 'string|max:255',
            'order' => 1,
            'display_name' => ['en' => 'Site Name', 'fr' => 'Nom du site', 'es' => 'Nombre del Sitio'],
            'description' => ['en' => 'The name of your site', 'fr' => 'Le nom de votre site', 'es' => 'El nombre de tu sitio'],
        ],
        [
            'group' => 'general',
            'key' => 'site_description',
            'value' => 'A TALL Stack Boilerplate',
            'type' => SettingType::TEXTAREA,
            'is_public' => true,
            'is_required' => false,
            'order' => 2,
            'display_name' => ['en' => 'Site Description', 'fr' => 'Description du site', 'es' => 'Descripción del Sitio'],
            'description' => ['en' => 'A brief description of your site', 'fr' => 'Une brève description de votre site', 'es' => 'Una breve descripción de tu sitio'],
        ],
        [
            'group' => 'general',
            'key' => 'default_language',
            'value' => 'en',
            'type' => SettingType::SELECT,
            'is_public' => true,
            'is_required' => true,
            'order' => 3,
            'display_name' => ['en' => 'Default Language', 'fr' => 'Langue par défaut', 'es' => 'Idioma Predeterminado'],
            'description' => ['en' => 'The default language for your site', 'fr' => 'La langue par défaut de votre site', 'es' => 'El idioma predeterminado de tu sitio'],
            'options' => [
                'en' => ['en' => 'English', 'fr' => 'French', 'es' => 'Spanish'],
                'fr' => ['en' => 'Anglais', 'fr' => 'Français', 'es' => 'Espagnol'],
                'es' => ['en' => 'Inglés', 'fr' => 'Francés', 'es' => 'Español'],
            ]
        ],
        [
            'group' => 'general',
            'key' => 'available_languages',
            'value' => json_encode(['en', 'fr', 'es']),
            'type' => SettingType::MULTISELECT,
            'is_public' => true,
            'is_required' => true,
            'order' => 4,
            'display_name' => ['en' => 'Available Languages', 'fr' => 'Langues disponibles', 'es' => 'Idiomas Disponibles'],
            'description' => ['en' => 'The languages available on your site', 'fr' => 'Les langues disponibles sur votre site', 'es' => 'Los idiomas disponibles en tu sitio'],
            'options' => [
                'en' => ['en' => 'English', 'fr' => 'French', 'es' => 'Spanish'],
                'fr' => ['en' => 'Anglais', 'fr' => 'Français', 'es' => 'Espagnol'],
                'es' => ['en' => 'Inglés', 'fr' => 'Francés', 'es' => 'Español'],
            ]
        ],

        // Appearance Settings
        [
            'group' => 'appearance',
            'key' => 'theme',
            'value' => 'light',
            'type' => SettingType::SELECT,
            'is_public' => true,
            'is_required' => true,
            'order' => 1,
            'display_name' => ['en' => 'Theme', 'fr' => 'Thème', 'es' => 'Tema'],
            'description' => ['en' => 'The theme for your application', 'fr' => 'Le thème de votre application', 'es' => 'El tema de tu aplicación'],
            'options' => [
                'en' => ['light' => 'Light', 'dark' => 'Dark', 'system' => 'System Default'],
                'fr' => ['light' => 'Clair', 'dark' => 'Sombre', 'system' => 'Défaut du système'],
                'es' => ['light' => 'Claro', 'dark' => 'Oscuro', 'system' => 'Predeterminado del sistema'],
            ]
        ],
        [
            'group' => 'appearance',
            'key' => 'show_logo_in_header',
            'value' => '1',
            'type' => SettingType::CHECKBOX,
            'is_public' => true,
            'is_required' => false,
            'order' => 2,
            'display_name' => ['en' => 'Show Logo in Header', 'fr' => 'Afficher le logo dans l\'en-tête', 'es' => 'Mostrar logo en la cabecera'],
            'description' => ['en' => 'Whether to show the logo in the header', 'fr' => 'Indique s\'il faut afficher le logo dans l\'en-tête', 'es' => 'Indica si se debe mostrar el logo en la cabecera'],
        ],
        [
            'group' => 'appearance',
            'key' => 'enable_dark_mode',
            'value' => '1',
            'type' => SettingType::CHECKBOX,
            'is_public' => true,
            'is_required' => false,
            'order' => 3,
            'display_name' => ['en' => 'Enable Dark Mode', 'fr' => 'Activer le mode sombre', 'es' => 'Habilitar modo oscuro'],
            'description' => ['en' => 'Whether to enable dark mode for the application', 'fr' => 'Indique s\'il faut activer le mode sombre pour l\'application', 'es' => 'Indica si se debe habilitar el modo oscuro para la aplicación'],
        ],

        // Notification Settings
        [
            'group' => 'notifications',
            'key' => 'email_notifications',
            'value' => '1',
            'type' => SettingType::CHECKBOX,
            'is_public' => false,
            'is_required' => false,
            'order' => 1,
            'display_name' => ['en' => 'Email Notifications', 'fr' => 'Notifications par e-mail', 'es' => 'Notificaciones por correo electrónico'],
            'description' => ['en' => 'Whether to send email notifications', 'fr' => 'Indique s\'il faut envoyer des notifications par e-mail', 'es' => 'Indica si se deben enviar notificaciones por correo electrónico'],
        ],
        [
            'group' => 'notifications',
            'key' => 'notification_frequency',
            'value' => 'immediately',
            'type' => SettingType::SELECT,
            'is_public' => false,
            'is_required' => true,
            'order' => 2,
            'display_name' => ['en' => 'Notification Frequency', 'fr' => 'Fréquence des notifications', 'es' => 'Frecuencia de Notificaciones'],
            'description' => ['en' => 'How often to send notifications', 'fr' => 'À quelle fréquence envoyer les notifications', 'es' => 'Con qué frecuencia enviar notificaciones'],
            'options' => [
                'en' => ['immediately' => 'Immediately', 'hourly' => 'Hourly Digest', 'daily' => 'Daily Digest', 'weekly' => 'Weekly Digest'],
                'fr' => ['immediately' => 'Immédiatement', 'hourly' => 'Résumé horaire', 'daily' => 'Résumé quotidien', 'weekly' => 'Résumé hebdomadaire'],
                'es' => ['immediately' => 'Inmediatamente', 'hourly' => 'Resumen por hora', 'daily' => 'Resumen diario', 'weekly' => 'Resumen semanal'],
            ]
        ],

        // Security Settings
        [
            'group' => 'security',
            'key' => 'require_two_factor_auth',
            'value' => '0',
            'type' => SettingType::CHECKBOX,
            'is_public' => false,
            'is_required' => false,
            'order' => 1,
            'display_name' => ['en' => 'Require Two-Factor Authentication', 'fr' => 'Exiger l\'authentification à deux facteurs', 'es' => 'Requerir autenticación de dos factores'],
            'description' => ['en' => 'Whether to require two-factor authentication for all users', 'fr' => 'Indique s\'il faut exiger l\'authentification à deux facteurs pour tous les utilisateurs', 'es' => 'Indica si se debe exigir autenticación de dos factores para todos los usuarios'],
        ],
        [
            'group' => 'security',
            'key' => 'session_timeout',
            'value' => '120',
            'type' => SettingType::NUMBER,
            'is_public' => false,
            'is_required' => true,
            'validation_rules' => 'integer|min:1',
            'order' => 2,
            'display_name' => ['en' => 'Session Timeout', 'fr' => 'Délai de session', 'es' => 'Tiempo de espera de sesión'],
            'description' => ['en' => 'The session timeout in minutes', 'fr' => 'Le délai de session en minutes', 'es' => 'El tiempo de espera de la sesión en minutos'],
        ],
        [
            'group' => 'security',
            'key' => 'log_failed_login_attempts',
            'value' => '1',
            'type' => SettingType::CHECKBOX,
            'is_public' => false,
            'is_required' => false,
            'order' => 3,
            'display_name' => ['en' => 'Log Failed Login Attempts', 'fr' => 'Journaliser les tentatives de connexion échouées', 'es' => 'Registrar intentos de inicio de sesión fallidos'],
            'description' => ['en' => 'Whether to log failed login attempts', 'fr' => 'Indique s\'il faut journaliser les tentatives de connexion échouées', 'es' => 'Indica si se deben registrar intentos de inicio de sesión fallidos'],
        ],
        [
            'group' => 'security',
            'key' => 'allow_user_registration',
            'value' => '1',
            'type' => SettingType::CHECKBOX,
            'is_public' => false,
            'is_required' => false,
            'order' => 4,
            'display_name' => ['en' => 'Allow User Registration', 'fr' => 'Autoriser l\'inscription des utilisateurs', 'es' => 'Permitir el registro de usuarios'],
            'description' => ['en' => 'Whether new users can register', 'fr' => 'Indique si les nouveaux utilisateurs peuvent s\'inscrire', 'es' => 'Indica si los nuevos usuarios pueden registrarse'],
        ],

        // Email Settings
        [
            'group' => 'email',
            'key' => 'mail_mailer',
            'value' => 'smtp',
            'type' => SettingType::TEXT,
            'is_public' => false,
            'is_required' => true,
            'order' => 1,
            'display_name' => ['en' => 'Mailer', 'fr' => 'Mailer', 'es' => 'Mailer'],
            'description' => ['en' => 'The mailer to use for sending emails', 'fr' => 'Le mailer à utiliser pour envoyer des e-mails', 'es' => 'El mailer a utilizar para enviar correos electrónicos'],
        ],
        [
            'group' => 'email',
            'key' => 'mail_host',
            'value' => 'smtp.mailtrap.io',
            'type' => SettingType::TEXT,
            'is_public' => false,
            'is_required' => true,
            'order' => 2,
            'display_name' => ['en' => 'Host', 'fr' => 'Hôte', 'es' => 'Host'],
            'description' => ['en' => 'The mail host', 'fr' => 'L\'hôte de messagerie', 'es' => 'El host de correo'],
        ],
        [
            'group' => 'email',
            'key' => 'mail_port',
            'value' => '2525',
            'type' => SettingType::NUMBER,
            'is_public' => false,
            'is_required' => true,
            'order' => 3,
            'display_name' => ['en' => 'Port', 'fr' => 'Port', 'es' => 'Puerto'],
            'description' => ['en' => 'The mail port', 'fr' => 'Le port de messagerie', 'es' => 'El puerto de correo'],
        ],
        [
            'group' => 'email',
            'key' => 'mail_username',
            'value' => '',
            'type' => SettingType::TEXT,
            'is_public' => false,
            'is_required' => false,
            'order' => 4,
            'display_name' => ['en' => 'Username', 'fr' => 'Nom d\'utilisateur', 'es' => 'Nombre de usuario'],
            'description' => ['en' => 'The mail username', 'fr' => 'Le nom d\'utilisateur de messagerie', 'es' => 'El nombre de usuario de correo'],
        ],
        [
            'group' => 'email',
            'key' => 'mail_password',
            'value' => '',
            'type' => SettingType::PASSWORD,
            'is_public' => false,
            'is_required' => false,
            'order' => 5,
            'display_name' => ['en' => 'Password', 'fr' => 'Mot de passe', 'es' => 'Contraseña'],
            'description' => ['en' => 'The mail password', 'fr' => 'Le mot de passe de messagerie', 'es' => 'La contraseña de correo'],
        ],
        [
            'group' => 'email',
            'key' => 'mail_encryption',
            'value' => 'tls',
            'type' => SettingType::TEXT,
            'is_public' => false,
            'is_required' => false,
            'order' => 6,
            'display_name' => ['en' => 'Encryption', 'fr' => 'Chiffrement', 'es' => 'Cifrado'],
            'description' => ['en' => 'The mail encryption', 'fr' => 'Le chiffrement de messagerie', 'es' => 'El cifrado de correo'],
        ],
        [
            'group' => 'email',
            'key' => 'mail_from_address',
            'value' => 'hello@example.com',
            'type' => SettingType::EMAIL,
            'is_public' => false,
            'is_required' => true,
            'order' => 7,
            'display_name' => ['en' => 'From Address', 'fr' => 'Adresse de l\'expéditeur', 'es' => 'Dirección del remitente'],
            'description' => ['en' => 'The from address for outgoing emails', 'fr' => 'L\'adresse de l\'expéditeur pour les e-mails sortants', 'es' => 'La dirección del remitente para los correos electrónicos salientes'],
        ],
        [
            'group' => 'email',
            'key' => 'mail_from_name',
            'value' => 'Example',
            'type' => SettingType::TEXT,
            'is_public' => false,
            'is_required' => true,
            'order' => 8,
            'display_name' => ['en' => 'From Name', 'fr' => 'Nom de l\'expéditeur', 'es' => 'Nombre del remitente'],
            'description' => ['en' => 'The from name for outgoing emails', 'fr' => 'Le nom de l\'expéditeur pour les e-mails sortants', 'es' => 'El nombre del remitente para los correos electrónicos salientes'],
        ],

        // Attachments Settings
        [
            'group' => 'attachments',
            'key' => 'attachments_max_upload_size_kb',
            'value' => '10240',
            'type' => SettingType::NUMBER,
            'is_public' => false,
            'is_required' => true,
            'order' => 1,
            'display_name' => ['en' => 'Max Upload Size (KB)', 'fr' => 'Taille de téléversement max (Ko)', 'es' => 'Tamaño máximo de subida (KB)'],
            'description' => ['en' => 'The maximum file size for uploads in kilobytes', 'fr' => 'La taille maximale des fichiers pour les téléversements en kilo-octets', 'es' => 'El tamaño máximo de archivo para subidas en kilobytes'],
        ],
        [
            'group' => 'attachments',
            'key' => 'attachments_image_optimization_enabled',
            'value' => '1',
            'type' => SettingType::CHECKBOX,
            'is_public' => false,
            'is_required' => false,
            'order' => 4,
            'display_name' => ['en' => 'Enable Image Optimization', 'fr' => 'Activer l\'optimisation des images', 'es' => 'Habilitar optimización de imágenes'],
            'description' => ['en' => 'Whether to optimize uploaded images', 'fr' => 'Indique s\'il faut optimiser les images téléversées', 'es' => 'Indica si se deben optimizar las imágenes subidas'],
        ],
        [
            'group' => 'attachments',
            'key' => 'attachments_image_quality',
            'value' => '80',
            'type' => SettingType::NUMBER,
            'is_public' => false,
            'is_required' => true,
            'order' => 5,
            'display_name' => ['en' => 'Image Quality', 'fr' => 'Qualité de l\'image', 'es' => 'Calidad de la imagen'],
            'description' => ['en' => 'The quality of optimized images', 'fr' => 'La qualité des images optimisées', 'es' => 'La calidad de las imágenes optimizadas'],
        ],
        [
            'group' => 'attachments',
            'key' => 'attachments_image_max_width',
            'value' => '1920',
            'type' => SettingType::NUMBER,
            'is_public' => false,
            'is_required' => true,
            'order' => 6,
            'display_name' => ['en' => 'Max Image Width', 'fr' => 'Largeur maximale de l\'image', 'es' => 'Ancho máximo de la imagen'],
            'description' => ['en' => 'The maximum width of optimized images', 'fr' => 'La largeur maximale des images optimisées', 'es' => 'El ancho máximo de las imágenes optimizadas'],
        ],
        [
            'group' => 'attachments',
            'key' => 'attachments_image_max_height',
            'value' => '1080',
            'type' => SettingType::NUMBER,
            'is_public' => false,
            'is_required' => true,
            'order' => 7,
            'display_name' => ['en' => 'Max Image Height', 'fr' => 'Hauteur maximale de l\'image', 'es' => 'Altura máxima de la imagen'],
            'description' => ['en' => 'The maximum height of optimized images', 'fr' => 'La hauteur maximale des images optimisées', 'es' => 'La altura máxima de las imágenes optimizadas'],
        ],
        [
            'group' => 'attachments',
            'key' => 'attachments_default_disk',
            'value' => 'public',
            'type' => SettingType::TEXT,
            'is_public' => false,
            'is_required' => true,
            'order' => 8,
            'display_name' => ['en' => 'Default Disk', 'fr' => 'Disque par défaut', 'es' => 'Disco por defecto'],
            'description' => ['en' => 'The default disk for storing attachments', 'fr' => 'Le disque par défaut pour stocker les pièces jointes', 'es' => 'El disco por defecto para almacenar archivos adjuntos'],
        ],

        // Site Identity Settings
        [
            'group' => 'site-identity',
            'key' => 'favicon',
            'type' => SettingType::FILE,
            'value' => '',
            'is_public' => true,
            'is_required' => false,
            'order' => 1,
            'display_name' => ['en' => 'Favicon', 'fr' => 'Favicon', 'es' => 'Favicon'],
            'description' => ['en' => 'The favicon for your site', 'fr' => 'Le favicon de votre site', 'es' => 'El favicon de tu sitio'],
        ],
        [
            'group' => 'site-identity',
            'key' => 'footer_copyright_text',
            'type' => SettingType::TEXTAREA,
            'value' => '© ' . date('Y') . ' My Awesome Site',
            'is_public' => true,
            'is_required' => false,
            'order' => 2,
            'display_name' => ['en' => 'Footer Copyright Text', 'fr' => 'Texte de copyright du pied de page', 'es' => 'Texto de copyright del pie de página'],
            'description' => ['en' => 'The copyright text to display in the footer', 'fr' => 'Le texte de copyright à afficher dans le pied de page', 'es' => 'El texto de copyright para mostrar en el pie de página'],
        ],

        // Integrations Settings
        [
            'group' => 'integrations',
            'key' => 'meta_tags',
            'type' => SettingType::TEXTAREA,
            'value' => '',
            'is_public' => true,
            'is_required' => false,
            'order' => 1,
            'display_name' => ['en' => 'Meta Tags', 'fr' => 'Balises méta', 'es' => 'Meta tags'],
            'description' => ['en' => 'Custom meta tags to add to the head of all pages', 'fr' => 'Balises méta personnalisées à ajouter à l\'en-tête de toutes les pages', 'es' => 'Meta tags personalizados para agregar al encabezado de todas las páginas'],
        ],
        [
            'group' => 'integrations',
            'key' => 'google_analytics_id',
            'type' => SettingType::TEXT,
            'value' => '',
            'is_public' => true,
            'is_required' => false,
            'order' => 2,
            'display_name' => ['en' => 'Google Analytics ID', 'fr' => 'ID Google Analytics', 'es' => 'ID de Google Analytics'],
            'description' => ['en' => 'Your Google Analytics ID (e.g. UA-12345678-1)', 'fr' => 'Votre ID Google Analytics (par ex. UA-12345678-1)', 'es' => 'Tu ID de Google Analytics (p. ej., UA-12345678-1)'],
        ],
        [
            'group' => 'integrations',
            'key' => 'google_tag_manager_id',
            'type' => SettingType::TEXT,
            'value' => '',
            'is_public' => true,
            'is_required' => false,
            'order' => 3,
            'display_name' => ['en' => 'Google Tag Manager ID', 'fr' => 'ID Google Tag Manager', 'es' => 'ID de Google Tag Manager'],
            'description' => ['en' => 'Your Google Tag Manager ID (e.g. GTM-123456)', 'fr' => 'Votre ID Google Tag Manager (par ex. GTM-123456)', 'es' => 'Tu ID de Google Tag Manager (p. ej., GTM-123456)'],
        ],
        [
            'group' => 'integrations',
            'key' => 'custom_header_code',
            'type' => SettingType::TEXTAREA,
            'value' => '',
            'is_public' => true,
            'is_required' => false,
            'order' => 4,
            'display_name' => ['en' => 'Custom Header Code', 'fr' => 'Code d\'en-tête personnalisé', 'es' => 'Código de encabezado personalizado'],
            'description' => ['en' => 'Custom code to add to the head of all pages', 'fr' => 'Code personnalisé à ajouter à l\'en-tête de toutes les pages', 'es' => 'Código personalizado para agregar al encabezado de todas las páginas'],
        ],
        [
            'group' => 'integrations',
            'key' => 'custom_body_code',
            'type' => SettingType::TEXTAREA,
            'value' => '',
            'is_public' => true,
            'is_required' => false,
            'order' => 5,
            'display_name' => ['en' => 'Custom Body Code', 'fr' => 'Code de corps personnalisé', 'es' => 'Código de cuerpo personalizado'],
            'description' => ['en' => 'Custom code to add to the body of all pages', 'fr' => 'Code personnalisé à ajouter au corps de toutes les pages', 'es' => 'Código personalizado para agregar al cuerpo de todas las páginas'],
        ],

        // Contact Information Settings
        [
            'group' => 'contact',
            'key' => 'primary_phone',
            'type' => SettingType::TEXT,
            'value' => '',
            'is_public' => true,
            'is_required' => false,
            'order' => 1,
            'display_name' => ['en' => 'Primary Phone', 'fr' => 'Téléphone principal', 'es' => 'Teléfono principal'],
            'description' => ['en' => 'Your primary contact phone number', 'fr' => 'Votre numéro de téléphone de contact principal', 'es' => 'Tu número de teléfono de contacto principal'],
        ],
        [
            'group' => 'contact',
            'key' => 'secondary_phone',
            'type' => SettingType::TEXT,
            'value' => '',
            'is_public' => true,
            'is_required' => false,
            'order' => 2,
            'display_name' => ['en' => 'Secondary Phone', 'fr' => 'Téléphone secondaire', 'es' => 'Teléfono secundario'],
            'description' => ['en' => 'Your secondary contact phone number', 'fr' => 'Votre numéro de téléphone de contact secondaire', 'es' => 'Tu número de teléfono de contacto secundario'],
        ],
        [
            'group' => 'contact',
            'key' => 'primary_email',
            'type' => SettingType::TEXT,
            'value' => '',
            'is_public' => true,
            'is_required' => false,
            'order' => 3,
            'display_name' => ['en' => 'Primary Email', 'fr' => 'E-mail principal', 'es' => 'Correo electrónico principal'],
            'description' => ['en' => 'Your primary contact email address', 'fr' => 'Votre adresse e-mail de contact principale', 'es' => 'Tu dirección de correo electrónico de contacto principal'],
        ],
        [
            'group' => 'contact',
            'key' => 'secondary_email',
            'type' => SettingType::TEXT,
            'value' => '',
            'is_public' => true,
            'is_required' => false,
            'order' => 4,
            'display_name' => ['en' => 'Secondary Email', 'fr' => 'E-mail secondaire', 'es' => 'Correo electrónico secundario'],
            'description' => ['en' => 'Your secondary contact email address', 'fr' => 'Votre adresse e-mail de contact secondaire', 'es' => 'Tu dirección de correo electrónico de contacto secundaria'],
        ],
        [
            'group' => 'contact',
            'key' => 'address',
            'type' => SettingType::TEXTAREA,
            'value' => '',
            'is_public' => true,
            'is_required' => false,
            'order' => 5,
            'display_name' => ['en' => 'Address', 'fr' => 'Adresse', 'es' => 'Dirección'],
            'description' => ['en' => 'Your physical address', 'fr' => 'Votre adresse physique', 'es' => 'Tu dirección física'],
        ],
        [
            'group' => 'contact',
            'key' => 'google_maps_embed',
            'type' => SettingType::TEXTAREA,
            'value' => '',
            'is_public' => true,
            'is_required' => false,
            'order' => 6,
            'display_name' => ['en' => 'Google Maps Embed', 'fr' => 'Intégration Google Maps', 'es' => 'Inserción de Google Maps'],
            'description' => ['en' => 'The embed code for your location on Google Maps', 'fr' => 'Le code d\'intégration pour votre emplacement sur Google Maps', 'es' => 'El código de inserción para tu ubicación en Google Maps'],
        ],

        // SEO Settings
        [
            'group' => 'seo',
            'key' => 'seo_title_template',
            'type' => SettingType::TEXT,
            'value' => '{title} | {site_name}',
            'is_public' => true,
            'is_required' => false,
            'order' => 1,
            'display_name' => ['en' => 'Title Template', 'fr' => 'Modèle de titre', 'es' => 'Plantilla de título'],
            'description' => ['en' => 'The template for your page titles', 'fr' => 'Le modèle pour les titres de vos pages', 'es' => 'La plantilla para los títulos de tus páginas'],
        ],
        [
            'group' => 'seo',
            'key' => 'seo_description_template',
            'type' => SettingType::TEXTAREA,
            'value' => '{description}',
            'is_public' => true,
            'is_required' => false,
            'order' => 2,
            'display_name' => ['en' => 'Description Template', 'fr' => 'Modèle de description', 'es' => 'Plantilla de descripción'],
            'description' => ['en' => 'The template for your page descriptions', 'fr' => 'Le modèle pour les descriptions de vos pages', 'es' => 'La plantilla para las descripciones de tus páginas'],
        ],
        [
            'group' => 'seo',
            'key' => 'seo_keywords',
            'type' => SettingType::TEXTAREA,
            'value' => '',
            'is_public' => true,
            'is_required' => false,
            'order' => 3,
            'display_name' => ['en' => 'Keywords', 'fr' => 'Mots-clés', 'es' => 'Palabras clave'],
            'description' => ['en' => 'The default keywords for your site', 'fr' => 'Les mots-clés par défaut pour votre site', 'es' => 'Las palabras clave por defecto para tu sitio'],
        ],
        [
            'group' => 'seo',
            'key' => 'seo_use_sitemap',
            'type' => SettingType::CHECKBOX,
            'value' => '1',
            'is_public' => true,
            'is_required' => false,
            'order' => 4,
            'display_name' => ['en' => 'Use Sitemap', 'fr' => 'Utiliser le sitemap', 'es' => 'Usar sitemap'],
            'description' => ['en' => 'Whether to generate a sitemap for your site', 'fr' => 'Indique s\'il faut générer un sitemap pour votre site', 'es' => 'Indica si se debe generar un sitemap para tu sitio'],
        ],
    ],
];